### Import Dependencies

In [1]:
import numpy as np
import pandas as pd

import pymongo

In [2]:
# asylum_seekers= pd.read_csv("resources/asylum_seekers.csv", dtype= asylum_seekers_dtypes, na_values= 99999)
asylum_seekers= pd.read_csv("resources/asylum_seekers.csv")
asylum_seekers_monthly= pd.read_csv("resources/asylum_seekers_monthly.csv")
demographics= pd.read_csv("resources/demographics.csv")
persons_of_concern= pd.read_csv("resources/persons_of_concern.csv")
resettlement= pd.read_csv("resources/resettlement.csv")
time_series= pd.read_csv("resources/time_series.csv")

C:\Users\Stewart\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3020: DtypeWarning: Columns (4,5,6,7,8,9,10,11,12,13) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
C:\Users\Stewart\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3020: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
C:\Users\Stewart\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3020: DtypeWarning: Columns (3,4,5,8,9,10) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [3]:
asylum_seekers_dtypes= {
    'Year': "float",
    'Country / territory of asylum/residence': "object",
    'Origin': "object",
    'RSD procedure type / level': "object",
    'Tota pending start-year': "float",
    'of which UNHCR-assisted(start-year)': "float",
    'Applied during year': "float",
    'decisions_recognized': "float",
    'decisions_other': "float",
    'Rejected': "float",
    'Otherwise closed': "float", 
    'Total decisions': "float",
    'Total pending end-year': "float",
    'of which UNHCR-assisted(end-year)': "float"
}

In [4]:
# Number of Records
print("Number of Records:\n"+str(len(asylum_seekers)))
print()
print(asylum_seekers.columns)

# Get rid of "*" character in dataset
asylum_seekers.replace("*","NaN",inplace=True)


# Make certain columns numeric
numeric_columns= ['Tota pending start-year', 'of which UNHCR-assisted(start-year)', 'Applied during year', 'decisions_recognized', 'decisions_other', 'Rejected', 'Otherwise closed', 'Total decisions', 'Total pending end-year', 'of which UNHCR-assisted(end-year)']

asylum_seekers= asylum_seekers.astype(asylum_seekers_dtypes)

Number of Records:
129720

Index(['Year', 'Country / territory of asylum/residence', 'Origin',
       'RSD procedure type / level', 'Tota pending start-year',
       'of which UNHCR-assisted(start-year)', 'Applied during year',
       'decisions_recognized', 'decisions_other', 'Rejected',
       'Otherwise closed', 'Total decisions', 'Total pending end-year',
       'of which UNHCR-assisted(end-year)'],
      dtype='object')

In [5]:
# Get rid of some columns
asylum_seekers= asylum_seekers[[
    'Year', 
    'Country / territory of asylum/residence',
    'Tota pending start-year',
    'Applied during year',
    'Total decisions',
    'Total pending end-year'
]]

# Get rid of Year 2000 to match other data

asylum_seekers= asylum_seekers.loc[(asylum_seekers["Year"] > 2000)]

print(min(asylum_seekers['Year']))
print(max(asylum_seekers['Year']))

len(asylum_seekers)

2001.0
2016.0

124567

In [6]:
#Groupby

asylum_seekers_groupby= asylum_seekers.groupby(["Year","Country / territory of asylum/residence"])
asylum_seekers_groupby_df= asylum_seekers_groupby.sum()
asylum_seekers_groupby_df.reset_index(inplace= True)

In [7]:
asylum_seekers_groupby_df

,Year,Country / territory of asylum/residence,Tota pending start-year,Applied during year,Total decisions,Total pending end-year
0,2001.0,Afghanistan,0.0,131.0,131.0,0.0
1,2001.0,Albania,4.0,160.0,93.0,71.0
2,2001.0,Algeria,310.0,28.0,265.0,108.0
3,2001.0,Angola,883.0,167.0,148.0,902.0
4,2001.0,Argentina,1274.0,495.0,226.0,1543.0
5,2001.0,Armenia,0.0,11.0,10.0,1.0
6,2001.0,Australia,10896.0,18113.0,17396.0,11582.0
7,2001.0,Austria,9945.0,30127.0,26494.0,15187.0
8,2001.0,Azerbaijan,3376.0,3539.0,364.0,6551.0
9,2001.0,Bahrain,2.0,7.0,9.0,0.0
10,2001.0,Bangladesh,2.0,27.0,8.0,21.0
11,2001.0,Belarus,411.0,215.0,272.0,354.0
12,2001.0,Belgium,1240.0,26028.0,5439.0,664.0
13,2001.0,Belize,35.0,38.0,51.0,22.0
14,2001.0,Benin,1994.0,1051.0,2819.0,226.0
15,2001.0,Bolivia (Plurinational State of),3.0,20.0,15.0,8.0
16,2001.0,Bosnia and Herzegovina,80.0,732.0,426.0,386.0
17,2001.0,Botswana,67.0,738.0,84.0,721.0
18,2001.0,Brazil,542.0,509.0,405.0,646.0
19,2001.0,Bulgaria,1316.0,2428.0,2240.0,1545.0
20,2001.0,Burkina Faso,314.0,76.0,140.0,250.0
21,2001.0,Burundi,5999.0,2062.0,67.0,7994.0
22,2001.0,Cambodia,167.0,1069.0,185.0,1051.0
23,2001.0,Cameroon,1638.0,1709.0,770.0,2577.0
24,2001.0,Canada,30175.0,44038.0,28317.0,45804.0
25,2001.0,Central African Rep.,1735.0,1937.0,0.0,3672.0
26,2001.0,Chad,544.0,453.0,351.0,646.0
27,2001.0,Chile,69.0,81.0,84.0,66.0
28,2001.0,China,12.0,18.0,29.0,1.0
29,2001.0,"China, Hong Kong SAR",51.0,631.0,214.0,468.0
...,...,...,...,...,...,...
2531,2016.0,Somalia,10105.0,3153.0,489.0,12777.0
2532,2016.0,South Africa,678532.0,35329.0,495609.0,218250.0
2533,2016.0,South Sudan,835.0,1055.0,103.0,1785.0
2534,2016.0,Spain,15733.0,16493.0,9199.0,20360.0
2535,2016.0,Sri Lanka,597.0,345.0,379.0,563.0
2536,2016.0,Sudan,12552.0,8535.0,5061.0,16021.0
2537,2016.0,Suriname,0.0,40.0,0.0,38.0
2538,2016.0,Swaziland,263.0,145.0,29.0,377.0
2539,2016.0,Sweden,156285.0,52674.0,126957.0,82580.0
2540,2016.0,Switzerland,8642.0,9042.0,9281.0,8808.0
2541,2016.0,Syrian Arab Rep.,4901.0,10499.0,3194.0,12185.0
2542,2016.0,Tajikistan,341.0,273.0,183.0,431.0
2543,2016.0,Thailand,8208.0,2585.0,5830.0,4956.0
2544,2016.0,The former Yugoslav Republic of Macedonia,5.0,741.0,737.0,10.0
2545,2016.0,Togo,740.0,203.0,181.0,767.0
2546,2016.0,Trinidad and Tobago,62.0,156.0,34.0,192.0
2547,2016.0,Tunisia,70.0,30.0,80.0,25.0
2548,2016.0,Turkey,212323.0,79583.0,46043.0,245856.0
2549,2016.0,Uganda,35758.0,30266.0,24161.0,41857.0
2550,2016.0,Ukraine,6334.0,1329.0,1284.0,6421.0
2551,2016.0,United Arab Emirates,417.0,506.0,325.0,600.0
2552,2016.0,United Kingdom,33840.0,50961.0,46406.0,32491.0
2553,2016.0,United Rep. of Tanzania,2150.0,6666.0,277.0,8539.0
2554,2016.0,United States of America,285558.0,204721.0,87829.0,439814.0
2555,2016.0,Uruguay,44.0,378.0,79.0,337.0
2556,2016.0,Vanuatu,0.0,0.0,0.0,0.0
2557,2016.0,Venezuela (Bolivarian Republic of),182.0,2886.0,2168.0,900.0
2558,2016.0,Yemen,9847.0,4309.0,5070.0,9083.0
2559,2016.0,Zambia,2383.0,3934.0,3016.0,3308.0
2560,2016.0,Zimbabwe,257.0,1501.0,800.0,948.0

In [8]:
asylum_seekers_groupby_df["Country / territory of asylum/residence"].value_counts()

United Arab Emirates                         16
Bangladesh                                   16
Kazakhstan                                   16
Bulgaria                                     16
Chile                                        16
Thailand                                     16
United Kingdom                               16
Morocco                                      16
South Africa                                 16
El Salvador                                  16
Belarus                                      16
Pakistan                                     16
Panama                                       16
Sierra Leone                                 16
France                                       16
Latvia                                       16
The former Yugoslav Republic of Macedonia    16
Nicaragua                                    16
Paraguay                                     16
China                                        16
Rwanda                                       16
Indonesia                                    16
Nepal                                        16
Peru                                         16
Lebanon                                      16
Guatemala                                    16
Niger                                        16
Israel                                       16
Guinea                                       16
Rep. of Korea                                16
                                             ..
Suriname                                      7
Curaçao                                       7
Sint Maarten (Dutch part)                     6
Jamaica                                       6
Lesotho                                       6
Uzbekistan                                    6
South Sudan                                   6
Saint Kitts and Nevis                         6
Madagascar                                    6
Guyana                                        5
British Virgin Islands                        5
Nauru                                         5
Turks and Caicos Islands                      5
Montserrat                                    4
Antigua and Barbuda                           4
Saint Vincent and the Grenadines              4
Solomon Islands                               3
Tonga                                         3
Lao People's Dem. Rep.                        3
Grenada                                       3
Myanmar                                       2
Monaco                                        2
Samoa                                         2
Micronesia (Federated States of)              2
Barbados                                      2
Dominica                                      2
Mauritius                                     1
Seychelles                                    1
Bonaire                                       1
Anguilla                                      1
Name: Country / territory of asylum/residence, Length: 190, dtype: int64

# The Merge

### Read in data from Stew

In [9]:
demographics_to_merge= pd.read_csv("resources/demographics_to_merge.csv")

In [10]:
residence_demo_merge= pd.merge(asylum_seekers,demographics_to_merge,how="left", on= ["Year","Country / territory of asylum/residence"])

In [11]:
residence_demo_merge["Year"]= residence_demo_merge["Year"].astype('int')
residence_demo_merge["Year"]= residence_demo_merge["Year"].astype('str')
residence_demo_merge.del
residence_demo_merge.head()

,Year,Country / territory of asylum/residence,Tota pending start-year,Applied during year,Total decisions,Total pending end-year,Unnamed: 0,F: Total,M: Total
0,2001,South Africa,0.0,0.0,NaN,4.0,NaN,NaN,NaN
1,2001,South Africa,8.0,0.0,7.0,1.0,NaN,NaN,NaN
2,2001,Uzbekistan,1235.0,2090.0,2009.0,1316.0,98.0,1730.0,2104.0
3,2001,United States of America,186.0,225.0,247.0,164.0,NaN,NaN,NaN
4,2001,United States of America,152.0,274.0,274.0,166.0,NaN,NaN,NaN

In [12]:
residence_demo_merge.to_csv("resources/residence_demo_merge.csv")

In [13]:
residence_demo_merge_dict= residence_demo_merge.to_dict('records')

In [14]:
test_residence_demo_merge= residence_demo_merge.set_index(["Year","Country / territory of asylum/residence"])

In [15]:
test_residence_demo_merge.to_json("resources/test_residence_demo_merge.json", orient="records")

# Mongo

In [16]:
conn= 'mongodb://localhost:27017'
client= pymongo.MongoClient(conn)

In [17]:
db= client["migration_db"]
collection= db.residence_demo_db

collection.insert_many(residence_demo_merge_dict)