In [1]:
import pandas as pd

In [3]:
asylum_seeker = pd.read_csv('asylum_seekers.csv')

FileNotFoundError: File b'asylum_seekers.csv' does not exist

In [3]:
asylum_seeker.replace('*', 'NaN', inplace=True)
asylum_seeker

,Year,Country / territory of asylum/residence,Origin,RSD procedure type / level,Tota pending start-year,of which UNHCR-assisted(start-year),Applied during year,decisions_recognized,decisions_other,Rejected,Otherwise closed,Total decisions,Total pending end-year,of which UNHCR-assisted(end-year)
0,2000,Zimbabwe,Afghanistan,G / FI,0,0,5,5,0,0,0,5,0,0
1,2000,South Africa,Afghanistan,G / FI,8,1,0,0,0,0,0,NaN,8,0
2,2000,Uzbekistan,Afghanistan,U / FI,265,265,2156,747,0,112,327,1186,1235,1235
3,2000,United States of America,Afghanistan,G / EO,196,0,225,151,0,31,68,250,171,0
4,2000,United States of America,Afghanistan,G / IN,193,0,218,182,0,51,40,273,150,0
5,2000,Ukraine,Afghanistan,G / FI,40,0,662,275,0,412,0,687,23,0
6,2000,Turkey,Afghanistan,U / FI,67,67,81,29,0,24,49,102,46,46
7,2000,Turkmenistan,Afghanistan,U / FI,416,416,169,126,0,121,210,457,128,128
8,2000,Tajikistan,Afghanistan,G / FI,2172,30,165,112,0,0,1992,2104,233,40
9,2000,Thailand,Afghanistan,U / AR,0,0,2,1,0,1,0,2,0,0
10,2000,Thailand,Afghanistan,U / FI,5,0,25,14,1,2,4,21,9,5
11,2000,Syrian Arab Rep.,Afghanistan,U / FI,311,0,94,62,0,138,180,380,25,0
12,2000,Sweden,Afghanistan,G / AR,0,0,0,0,44,124,1,169,0,0
13,2000,Sweden,Afghanistan,G / FI,0,0,374,33,563,78,13,687,0,0
14,2000,Slovenia,Afghanistan,G / FI,4,0,247,0,0,2,11,13,238,0
15,2000,Slovakia,Afghanistan,G / FI,90,0,624,5,0,28,559,592,122,0
16,2000,Serbia and Kosovo (S/RES/1244 (1999)),Afghanistan,U / FI,0,0,7,0,0,5,2,7,0,0
17,2000,Russian Federation,Afghanistan,G / FI,1009,0,1088,160,0,1317,0,1477,620,0
18,2000,Romania,Afghanistan,G / FI,10,10,282,27,35,191,0,253,0,0
19,2000,Portugal,Afghanistan,G / FI,0,0,4,0,1,1,0,2,0,0
20,2000,Poland,Afghanistan,G / AR,0,0,0,0,0,2,0,2,0,0
21,2000,Poland,Afghanistan,G / FI,0,0,299,0,0,8,392,400,0,0
22,2000,Nepal,Afghanistan,G / FI,2,0,0,0,0,0,2,2,0,0
23,2000,Norway,Afghanistan,G / AR,0,0,0,0,0,57,0,57,0,0
24,2000,Norway,Afghanistan,G / FI,0,0,326,16,104,519,17,656,0,0
25,2000,Netherlands,Afghanistan,G / JR,0,0,0,0,0,0,0,NaN,1976,0
26,2000,Netherlands,Afghanistan,G / AR,0,0,0,482,254,2791,637,4164,4842,0
27,2000,Netherlands,Afghanistan,G / FI,0,0,5055,324,2345,205,2340,5214,4113,0
28,2000,Malaysia,Afghanistan,U / FI,10,0,123,23,4,79,20,126,7,7
29,2000,Mozambique,Afghanistan,G / FI,1,1,0,0,0,0,0,NaN,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129690,2016,Kenya,Zimbabwe,J / AR,NaN,NaN,0,0,0,0,0,NaN,NaN,NaN
129691,2016,Kenya,Zimbabwe,J / FI,NaN,NaN,NaN,NaN,0,0,0,NaN,NaN,NaN
129692,2016,Rep. of Korea,Zimbabwe,G / FA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
129693,2016,Lesotho,Zimbabwe,G / FI,NaN,0,0,0,NaN,NaN,NaN,NaN,0,0
129694,2016,Luxembourg,Zimbabwe,G / RA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
129695,2016,Luxembourg,Zimbabwe,G / AR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0
129696,2016,Luxembourg,Zimbabwe,G / JR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0
129697,2016,Luxembourg,Zimbabwe,G / FI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
129698,2016,Malawi,Zimbabwe,G / FI,0,0,NaN,0,0,0,NaN,NaN,0,0
129699,2016,Malaysia,Zimbabwe,U / FI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
129700,2016,Namibia,Zimbabwe,G / FI,76,61,9,NaN,NaN,NaN,NaN,NaN,85,85
129701,2016,Netherlands,Zimbabwe,G / FI,6,NaN,12,NaN,NaN,8,NaN,11,7,NaN
129702,2016,Netherlands,Zimbabwe,G / RA,NaN,NaN,5,0,NaN,NaN,NaN,NaN,NaN,NaN
129703,2016,Norway,Zimbabwe,G / FI,NaN,NaN,5,NaN,NaN,NaN,NaN,5,NaN,NaN
129704,2016,Norway,Zimbabwe,G / AR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
129705,2016,New Zealand,Zimbabwe,G / FI,NaN,0,8,NaN,0,NaN,0,NaN,5,NaN
129706,2016,Philippines,Zimbabwe,G / FA,NaN,NaN,0,NaN,0,0,0,NaN,0,0
129707,2016,Portugal,Zimbabwe,G / FI,NaN,NaN,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN
129708,2016,Romania,Zimbabwe,G / FI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
129709,2016,Russian Federation,Zimbabwe,G / FI,NaN,NaN,NaN,0,0,0,NaN,NaN,0,0
129710,2016,Sweden,Zimbabwe,G / RA,NaN,NaN,NaN,0,0,NaN,0,NaN,NaN,NaN
129711,2016,Sweden,Zimbabwe,G / AR,0,NaN,13,0,0,NaN,NaN,7,6,NaN
129712,2016,Sweden,Zimbabwe,G / FI,7,NaN,18,NaN,0,5,15,21,NaN,NaN
129713,2016,Turkey,Zimbabwe,U / FI,NaN,NaN,0,0,NaN,0,0,NaN,NaN,NaN
129714,2016,Ukraine,Zimbabwe,G / JR,5,0,0,0,NaN,0,0,NaN,5,0
129715,2016,United States of America,Zimbabwe,G / IN,232,NaN,229,16,NaN,NaN,10,28,435,NaN
129716,2016,United States of America,Zimbabwe,G / EO,142,NaN,12,NaN,NaN,NaN,23,31,138,NaN
129717,2016,South Africa,Zimbabwe,G / AR,94,9,NaN,NaN,NaN,NaN,94,94,0,NaN
129718,2016,South Africa,Zimbabwe,G / FI,41238,4124,7964,73,NaN,7869,NaN,7942,41260,NaN
129719,2016,Zambia,Zimbabwe,G / FI,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
asylum_seeker.set_index('Year', inplace=True)
asylum_seeker

,Country / territory of asylum/residence,Origin,RSD procedure type / level,Tota pending start-year,of which UNHCR-assisted(start-year),Applied during year,decisions_recognized,decisions_other,Rejected,Otherwise closed,Total decisions,Total pending end-year,of which UNHCR-assisted(end-year)
Year,,,,,,,,,,,,,
2000,Zimbabwe,Afghanistan,G / FI,0,0,5,5,0,0,0,5,0,0
2000,South Africa,Afghanistan,G / FI,8,1,0,0,0,0,0,NaN,8,0
2000,Uzbekistan,Afghanistan,U / FI,265,265,2156,747,0,112,327,1186,1235,1235
2000,United States of America,Afghanistan,G / EO,196,0,225,151,0,31,68,250,171,0
2000,United States of America,Afghanistan,G / IN,193,0,218,182,0,51,40,273,150,0
2000,Ukraine,Afghanistan,G / FI,40,0,662,275,0,412,0,687,23,0
2000,Turkey,Afghanistan,U / FI,67,67,81,29,0,24,49,102,46,46
2000,Turkmenistan,Afghanistan,U / FI,416,416,169,126,0,121,210,457,128,128
2000,Tajikistan,Afghanistan,G / FI,2172,30,165,112,0,0,1992,2104,233,40
2000,Thailand,Afghanistan,U / AR,0,0,2,1,0,1,0,2,0,0
2000,Thailand,Afghanistan,U / FI,5,0,25,14,1,2,4,21,9,5
2000,Syrian Arab Rep.,Afghanistan,U / FI,311,0,94,62,0,138,180,380,25,0
2000,Sweden,Afghanistan,G / AR,0,0,0,0,44,124,1,169,0,0
2000,Sweden,Afghanistan,G / FI,0,0,374,33,563,78,13,687,0,0
2000,Slovenia,Afghanistan,G / FI,4,0,247,0,0,2,11,13,238,0
2000,Slovakia,Afghanistan,G / FI,90,0,624,5,0,28,559,592,122,0
2000,Serbia and Kosovo (S/RES/1244 (1999)),Afghanistan,U / FI,0,0,7,0,0,5,2,7,0,0
2000,Russian Federation,Afghanistan,G / FI,1009,0,1088,160,0,1317,0,1477,620,0
2000,Romania,Afghanistan,G / FI,10,10,282,27,35,191,0,253,0,0
2000,Portugal,Afghanistan,G / FI,0,0,4,0,1,1,0,2,0,0
2000,Poland,Afghanistan,G / AR,0,0,0,0,0,2,0,2,0,0
2000,Poland,Afghanistan,G / FI,0,0,299,0,0,8,392,400,0,0
2000,Nepal,Afghanistan,G / FI,2,0,0,0,0,0,2,2,0,0
2000,Norway,Afghanistan,G / AR,0,0,0,0,0,57,0,57,0,0
2000,Norway,Afghanistan,G / FI,0,0,326,16,104,519,17,656,0,0
2000,Netherlands,Afghanistan,G / JR,0,0,0,0,0,0,0,NaN,1976,0
2000,Netherlands,Afghanistan,G / AR,0,0,0,482,254,2791,637,4164,4842,0
2000,Netherlands,Afghanistan,G / FI,0,0,5055,324,2345,205,2340,5214,4113,0
2000,Malaysia,Afghanistan,U / FI,10,0,123,23,4,79,20,126,7,7
2000,Mozambique,Afghanistan,G / FI,1,1,0,0,0,0,0,NaN,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2016,Kenya,Zimbabwe,J / AR,NaN,NaN,0,0,0,0,0,NaN,NaN,NaN
2016,Kenya,Zimbabwe,J / FI,NaN,NaN,NaN,NaN,0,0,0,NaN,NaN,NaN
2016,Rep. of Korea,Zimbabwe,G / FA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
2016,Lesotho,Zimbabwe,G / FI,NaN,0,0,0,NaN,NaN,NaN,NaN,0,0
2016,Luxembourg,Zimbabwe,G / RA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2016,Luxembourg,Zimbabwe,G / AR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0
2016,Luxembourg,Zimbabwe,G / JR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0
2016,Luxembourg,Zimbabwe,G / FI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2016,Malawi,Zimbabwe,G / FI,0,0,NaN,0,0,0,NaN,NaN,0,0
2016,Malaysia,Zimbabwe,U / FI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2016,Namibia,Zimbabwe,G / FI,76,61,9,NaN,NaN,NaN,NaN,NaN,85,85
2016,Netherlands,Zimbabwe,G / FI,6,NaN,12,NaN,NaN,8,NaN,11,7,NaN
2016,Netherlands,Zimbabwe,G / RA,NaN,NaN,5,0,NaN,NaN,NaN,NaN,NaN,NaN
2016,Norway,Zimbabwe,G / FI,NaN,NaN,5,NaN,NaN,NaN,NaN,5,NaN,NaN
2016,Norway,Zimbabwe,G / AR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2016,New Zealand,Zimbabwe,G / FI,NaN,0,8,NaN,0,NaN,0,NaN,5,NaN
2016,Philippines,Zimbabwe,G / FA,NaN,NaN,0,NaN,0,0,0,NaN,0,0
2016,Portugal,Zimbabwe,G / FI,NaN,NaN,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2016,Romania,Zimbabwe,G / FI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2016,Russian Federation,Zimbabwe,G / FI,NaN,NaN,NaN,0,0,0,NaN,NaN,0,0
2016,Sweden,Zimbabwe,G / RA,NaN,NaN,NaN,0,0,NaN,0,NaN,NaN,NaN
2016,Sweden,Zimbabwe,G / AR,0,NaN,13,0,0,NaN,NaN,7,6,NaN
2016,Sweden,Zimbabwe,G / FI,7,NaN,18,NaN,0,5,15,21,NaN,NaN
2016,Turkey,Zimbabwe,U / FI,NaN,NaN,0,0,NaN,0,0,NaN,NaN,NaN
2016,Ukraine,Zimbabwe,G / JR,5,0,0,0,NaN,0,0,NaN,5,0
2016,United States of America,Zimbabwe,G / IN,232,NaN,229,16,NaN,NaN,10,28,435,NaN
2016,United States of America,Zimbabwe,G / EO,142,NaN,12,NaN,NaN,NaN,23,31,138,NaN
2016,South Africa,Zimbabwe,G / AR,94,9,NaN,NaN,NaN,NaN,94,94,0,NaN
2016,South Africa,Zimbabwe,G / FI,41238,4124,7964,73,NaN,7869,NaN,7942,41260,NaN
2016,Zambia,Zimbabwe,G / FI,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
asylum_seeker = asylum_seeker[['Origin', 'Applied during year', 'Total decisions']]
asylum_seeker.head()

           Origin Applied during year Total decisions
Year
2000  Afghanistan                   5               5
2000  Afghanistan                   0             NaN
2000  Afghanistan                2156            1186
2000  Afghanistan                 225             250
2000  Afghanistan                 218             273

In [10]:
asylum_seeker_dtypes = {
    'Origin': 'str',
    'Applied during year': 'float',
    'Total decisions': 'float'
}

asylum_seeker= asylum_seeker.astype(asylum_seeker_dtypes)

In [11]:
asylum_seeker_groupby = asylum_seeker.groupby(['Year', 'Origin']).sum()
asylum_seeker_groupby

                                                Applied during year  \
Year Origin
2000 Afghanistan                                           291283.0
     Albania                                                 9765.0
     Algeria                                                10312.0
     Andorra                                                    1.0
     Angola                                                  7160.0
     Antigua and Barbuda                                        7.0
     Argentina                                               1631.0
     Armenia                                                10726.0
     Australia                                                  9.0
     Austria                                                   13.0
     Azerbaijan                                              5054.0
     Bahamas                                                    8.0
     Bahrain                                                   50.0
     Bangladesh                                              8014.0
     Barbados                                                  13.0
     Belarus                                                 2830.0
     Belgium                                                   31.0
     Belize                                                    15.0
     Benin                                                    149.0
     Bhutan                                                   153.0
     Bolivia (Plurinational State of)                         209.0
     Bosnia and Herzegovina                                 12552.0
     Botswana                                                   1.0
     Brazil                                                   415.0
     Brunei Darussalam                                          1.0
     Bulgaria                                                3374.0
     Burkina Faso                                             816.0
     Burundi                                                 2758.0
     Cabo Verde                                                21.0
     Cambodia                                                 752.0
...                                                             ...
2016 Tajikistan                                              3629.0
     Thailand                                                 534.0
     The former Yugoslav Republic of Macedonia               9341.0
     Tibetan                                                   12.0
     Timor-Leste                                                0.0
     Togo                                                    1938.0
     Tonga                                                     68.0
     Trinidad and Tobago                                      134.0
     Tunisia                                                 3079.0
     Turkey                                                 19550.0
     Turkmenistan                                             480.0
     Turks and Caicos Islands                                   0.0
     Tuvalu                                                     6.0
     Uganda                                                  3464.0
     Ukraine                                                41706.0
     United Arab Emirates                                      93.0
     United Kingdom                                            74.0
     United Rep. of Tanzania                                  801.0
     United States of America                                 325.0
     Uruguay                                                   33.0
     Uzbekistan                                              1876.0
     Vanuatu                                                    0.0
     Various/Unknown                                        29842.0
     Venezuela (Bolivarian Republic of)                     34338.0
     Viet Nam                                                5722.0
     Wallis and Futuna Islands                                  0.0
     Western Sahara                                          1459.0
     Yemen                                                   9220.0
     Zambia                                                   211.0
     Zimbabwe                                                9635.0

                                                Total decisions
Year Origin
2000 Afghanistan                                       274044.0
     Albania                                             7207.0
     Algeria                                            10161.0
     Andorra                                                0.0
     Angola                                              7098.0
     Antigua and Barbuda                                    4.0
     Argentina                                            682.0
     Armenia                                            10717.0
     Australia                                             11.0
     Austria                                               13.0
     Azerbaijan                                          6577.0
     Bahamas                                               12.0
     Bahrain                                               55.0
     Bangladesh                                          9037.0
     Barbados                                              15.0
     Belarus                                             1703.0
     Belgium                                               18.0
     Belize                                                16.0
     Benin                                                104.0
     Bhutan                                               169.0
     Bolivia (Plurinational State of)                     208.0
     Bosnia and Herzegovina                             12528.0
     Botswana                                               1.0
     Brazil                                               648.0
     Brunei Darussalam                                      1.0
     Bulgaria                                            1829.0
     Burkina Faso                                         604.0
     Burundi                                             2065.0
     Cabo Verde                                            14.0
     Cambodia                                             907.0
...                                                         ...
2016 Tajikistan                                          1945.0
     Thailand                                             233.0
     The former Yugoslav Republic of Macedonia          21297.0
     Tibetan                                                6.0
     Timor-Leste                                            0.0
     Togo                                                1512.0
     Tonga                                                 74.0
     Trinidad and Tobago                                  123.0
     Tunisia                                             3776.0
     Turkey                                              9095.0
     Turkmenistan                                         448.0
     Turks and Caicos Islands                               0.0
     Tuvalu                                                 6.0
     Uganda                                              3934.0
     Ukraine                                            41801.0
     United Arab Emirates                                  11.0
     United Kingdom                                        47.0
     United Rep. of Tanzania                              766.0
     United States of America                             290.0
     Uruguay                                               10.0
     Uzbekistan                                          1671.0
     Vanuatu                                                0.0
     Various/Unknown                                   495894.0
     Venezuela (Bolivarian Republic of)                  3017.0
     Viet Nam                                            4809.0
     Wallis and Futuna Islands                              0.0
     Western Sahara                                       896.0
     Yemen                                               3375.0
     Zambia                                               212.0
     Zimbabwe                                            9159.0

[3425 rows x 2 columns]

In [15]:
residence_demo_merge = pd.read_csv('./residence_demo_merge.csv')
residence_demo_merge.set_index('Year', inplace=True)
residence_demo_merge.head(20)

,Unnamed: 0,Country / territory of asylum/residence,Tota pending start-year,Applied during year,Total decisions,Total pending end-year,Unnamed: 0.1,F: Total,M: Total
Year,,,,,,,,,
2001,0,South Africa,0.0,0.0,NaN,4.0,NaN,NaN,NaN
2001,1,South Africa,8.0,0.0,7.0,1.0,NaN,NaN,NaN
2001,2,Uzbekistan,1235.0,2090.0,2009.0,1316.0,98.0,1730.0,2104.0
2001,3,United States of America,186.0,225.0,247.0,164.0,NaN,NaN,NaN
2001,4,United States of America,152.0,274.0,274.0,166.0,NaN,NaN,NaN
2001,5,Ukraine,23.0,373.0,324.0,72.0,95.0,546.0,1245.0
2001,6,Turkey,46.0,431.0,170.0,307.0,92.0,2237.0,3290.0
2001,7,Tunisia,0.0,1.0,1.0,0.0,91.0,43.0,54.0
2001,8,Turkmenistan,128.0,382.0,421.0,89.0,93.0,5480.0,8061.0
2001,9,Tajikistan,233.0,720.0,577.0,376.0,87.0,6260.0,8872.0
2001,10,Thailand,9.0,21.0,25.0,5.0,88.0,53513.0,57198.0
2001,11,Syrian Arab Rep.,36.0,136.0,161.0,11.0,86.0,1534.0,1737.0
2001,12,Sweden,0.0,0.0,529.0,0.0,NaN,NaN,NaN
2001,13,Sweden,0.0,593.0,349.0,0.0,NaN,NaN,NaN
2001,14,Slovenia,238.0,66.0,296.0,8.0,81.0,1017.0,650.0
2001,15,Slovakia,122.0,4315.0,2839.0,1598.0,NaN,NaN,NaN
2001,16,Serbia and Kosovo (S/RES/1244 (1999)),0.0,48.0,22.0,26.0,79.0,327781.0,303686.0
2001,17,Singapore,0.0,1.0,1.0,0.0,80.0,1.0,3.0
2001,18,Saudi Arabia,8.0,78.0,43.0,43.0,77.0,1844.0,3658.0
2001,19,Russian Federation,620.0,1300.0,1251.0,669.0,NaN,NaN,NaN